name: Deploy PROD

permissions:
  contents: write
  pull-requests: write
  actions: read

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  manual-approval:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    runs-on: [self-hosted]
    steps:
      - name: Wait for manual approval (only on PRs)
        if: ${{ github.event_name == 'pull_request' }}
        uses: hmarr/auto-approve-action@v2
        
  prod-network:
    needs: manual-approval
    uses: ./.github/workflows/component-deployment.yml
    with:
      env: prod
      component: network
    secrets: inherit
  
  prod-compute:
    needs: prod-network
    uses: ./.github/workflows/component-deployment.yml
    with:
      env: prod
      component: compute
    secrets: inherit