name: Deploy DEV & STAGE

permissions:
  contents: write
  pull-requests: write
  actions: read

env:
  OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
  OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
  OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
  TF_HTTP_USERNAME: ${{ secrets.TF_HTTP_USERNAME }}
  TF_HTTP_PASSWORD: ${{ secrets.TF_HTTP_PASSWORD }}

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  deploy-network:
    runs-on: [ self-hosted ]
    strategy:
      matrix:
        env: [dev, stage]
    environment: ${{ matrix.env }}
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.10.6

      - name: Create tfvars file
        run: echo "$TFVARS_CONTENT" > terraform.auto.tfvars
        working-directory: ./stacks/${{ matrix.env }}/network
        env:
          TFVARS_CONTENT: ${{ secrets.TFVARS_CONTENT }}

      - name: OpenTofu Init
        run: tofu init -input=false -no-color
        working-directory: ./stacks/${{ matrix.env }}/network

      - name: OpenTofu Plan
        run: tofu plan -input=false -no-color -out=tfplan
        working-directory: ./stacks/${{ matrix.env }}/network

      - name: OpenTofu Apply
        run: tofu apply -input=false -no-color -auto-approve tfplan
        working-directory: ./stacks/${{ matrix.env }}/network
  
  deploy-compute:
    needs: deploy-network
    runs-on: [ self-hosted ]
    strategy:
      matrix:
        env: [dev, stage]
    environment: ${{ matrix.env }}
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.10.6

      - name: Create tfvars file
        run: echo "$TFVARS_CONTENT" > terraform.auto.tfvars
        working-directory: ./stacks/${{ matrix.env }}/compute
        env:
          TFVARS_CONTENT: ${{ secrets.TFVARS_CONTENT }}

      - name: OpenTofu Init
        run: tofu init -input=false -no-color
        working-directory: ./stacks/${{ matrix.env }}/compute

      - name: OpenTofu Plan
        run: tofu plan -input=false -no-color -out=tfplan
        working-directory: ./stacks/${{ matrix.env }}/compute

      - name: OpenTofu Apply
        run: tofu apply -input=false -no-color -auto-approve tfplan
        working-directory: ./stacks/${{ matrix.env }}/compute
  
  create-pr:
    needs: [deploy-network, deploy-compute]
    runs-on: [ self-hosted ]
    steps:
      - name: Authenticate GH CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ~/.config/gh
          echo "git.ntnu.no:
            user: github-actions[bot]
            oauth_token: ${GH_TOKEN}
            git_protocol: https
          " > ~/.config/gh/hosts.yml

      - name: Verify GH auth
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth status -h git.ntnu.no

      - name: Push branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git config --global credential.helper store
          echo "https://x-access-token:${GH_TOKEN}@git.ntnu.no" > ~/.git-credentials

          git fetch origin main
          git checkout -B stage-to-prod
          git push --force --set-upstream origin stage-to-prod

      - name: Create PR for Prod
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Stage → Prod" \
            --body "Promoting stage changes to production" \
            --base main \
            --head stage-to-prod \
            --fill
