# This is a basic workflow to help you get started with Actions

name: Simple Terraform CI

permissions:
  contents: read
  actions: read

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    permissions:
      contents: read
      actions: read
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v4
      
      - name: OpenTofu Validate
        run: tofu validate
        working-directory: ./stacks/prod
      
      - name: Security Scan (tfsec)
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
          ./tfsec ./stacks/prod

  deploy-prod:
    permissions:
      contents: write
      actions: write
    #needs: deploy-staging
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v4

      - name: OpenTofu Init
        run: tofu init
        working-directory: ./stacks/prod

      - name: OpenTofu Plan (manual approval required)
        run: tofu plan -auto-approve
        working-directory: ./stacks/prod
